### ISSUE TITLE
Incorrect console table output ...

### ISSUE THREAD

**Issue by scramatte** [efureev/laravel-trees#15]
Hello,

I've got some issue with console table output. As you can see on my screenshot bellow  uuid are output as decimal instead of proper "uuid"  and  nodes are not ordered.

<img width="364" alt="image" src="https://user-images.githubusercontent.com/188766/158082694-c25448ae-5056-43fe-ae6c-36cdb4a9c004.png">

For the uuid as decimal I've no idea but  for unordered issue  I believe that your example should be

`$collection = Structure::orderBy('lft')->get();`

Instead of 

`$collection = Structure::all();`

Regards

**Comment by scramatte** [comment]
Ok, I've beed able fix uuid issue too ... sorry for noise.
When You set id as "uuid" type instead of int you need to prepare more things before.

For sure you have already done it internally with some mechanism  but I probably  misunderstand something and/or documentation is incorrect/incomplete...

Anyways , to get it working take a look to my workaround bellow.  I hope this helps.

1. Add following to your nestedtree model

```
<?php
namespace App\Models;

use App\Traits\Uuid;
use Fureev\Trees\NestedSetTrait;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use Uuid, NestedSetTrait;
 
    public $incrementing = false;
    protected $keyType = 'uuid';
...

```

2. Create trait to generate Uuid on insert.

```
<?php

namespace App\Traits;

use Illuminate\Support\Str;

trait Uuid
{
    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            try {
                $model->id = (string) Str::uuid();
            } catch (UnsatisfiedDependencyException $e) {
                abort(500, $e->getMessage());
            }
        });
    }
}
```

**Comment by efureev** [comment]
To custom generate ID you should use `generateTreeId` into you Model.

In all cases, including tests, ID-value generated by DB (`uuid_generate_v4()`).
