### ISSUE TITLE
custom DB fields? 

### ISSUE THREAD

**Issue by michabbb** [efureev/laravel-trees#2]
hi, I read the docu several times but sorry, I don't get it: I guess I understand that I have to choose if the primary key of my tree table is int or uuid, okay. but where do I define the other column, where the relation is saved? let's say my table has "cat_id" (primary key of my catgeroy table) and I would like to use "cat_parent" as column for the relations, how do I have to configure my model to make this working?

thanks a lot!

**Comment by efureev** [comment]
it couldn't be simpler:  
Model and tree's settings: https://github.com/efureev/laravel-trees/blob/master/tests/models/CustomModel.php

You may setup every field using in Tree.
