### ISSUE TITLE
[info] handling tree with separate table

### ISSUE THREAD

**Issue by IAndreaGiuseppe** [efureev/laravel-trees#20]
Hi I have to ask informations for a specific design.

I have a db structure that consist of 2 table:

A: id, name
B: aid, parent_id

Table A has the unique nodes.
Table B handle the tree structure. To note that on table B I dont have roots node because the parent_id cannot be `null` then the 2 table has to work together. (I can overwrite this if necessary)

Is it possible to handle this kind of design with your package?

Thanks

**Comment by efureev** [comment]
Sorry, no )
