### ISSUE TITLE
Call to a member function getKey() on null

### ISSUE THREAD

**Issue by muhammedfisek** [efureev/laravel-trees#23]
It gives an error if the right ID or left ID value of the end user is empty.

<img width="313" alt="image" src="https://user-images.githubusercontent.com/3823032/219250669-51a74697-b54b-472e-a0f2-30781ac56eb2.png">

The end user is also included in the tree. But I can't include it with this build.

how can i solve this?

**Comment by efureev** [comment]
I'm sorry, but I didn't get you. Describe the problem in more detail. You can write tests and make MR

**Comment by muhammedfisek** [comment]
Hi @efureev,

I begin with Damla to create the tree structure. Arzum, Vildan and Mert are added to this properly. Mert has Standartmus on his right. But standartmus' right and left are empty. It definitely requires occupancy in the library you have written. 

If the right is empty, it does not add the user. That's my problem, how can we fix this error? Below I indicate you the sample codes and where it throws the exception.

 
$customers = \App\Models\Customer::where('user_group', 'bayi')->where('customer_id', '<=', 90000001)->get()->keyBy('customer_id')->toArray();
    
    foreach ($customers as $customer) {
        if ($customer['sponsor_id'] == 0) {
            \App\Models\Seller::make($customer)->makeRoot()->save();
        }
        if (isset($customer['right_id']) && $customer['right_id'] > 0) {
            $rightCustomer = $customers[$customer['right_id']];
            if (!isset($rightCustomer['right_id'])) {
                $rightCustomer['right_id'] = 0;
                $rightCustomer['left_id'] = 0;
            }
            if (isset($rightCustomer['right_id']) && $rightCustomer['right_id'] > 0) {
                // echo "-S:" . $rightCustomer['customer_id'] . "\n<br>";
                $node = \App\Models\Seller::make($rightCustomer);
                $node->appendTo(\App\Models\Seller::firstWhere('customer_id', $customer['customer_id']))->save();
            } else {
                //not set right ; error:
                echo "\nhatastart:\n";;
                print_r($rightCustomer);
                echo "\nhataend\n";
            }
        }
    }

<img width="617" alt="image" src="https://user-images.githubusercontent.com/3823032/219422108-aaa9c40b-3a20-456d-989f-34b11a431b11.png">

<img width="417" alt="image" src="https://user-images.githubusercontent.com/3823032/219422811-677a00f8-5381-48b6-bff0-0a67d3068854.png">


And my Seller Model;

protected $primaryKey = 'customer_id';

    protected $table = 'sellers';
    protected $collection = 'sellers';
    protected $guarded = [];
    protected $hidden = ['created_at', 'password', 'updated_at'];
    protected $dates = ['active_last_date', 'created_at', 'updated_at', 'deleted_at'];

    protected static function buildTreeConfig(): Base
    {
        // return new Base(true);
        return Base::make()
            ->setMultiTree(true)
            ->setAttribute('parent', ParentAttribute::make()->setName('sponsor_id'))
            ->setAttribute('left', LeftAttribute::make()->setName('lft'))
            ->setAttribute('right', RightAttribute::make()->setName('rgt'))
            ->setAttribute('level', LevelAttribute::make()->setName('lvl'));
    }

**Comment by efureev** [comment]
What's your DB?

**Comment by muhammedfisek** [comment]
> 

Mongodb 5.6

**Comment by efureev** [comment]
The library is designed to work only with sql-databases. Mainly with Postgres, MySQL
