### ISSUE TITLE
Error after insert new node

### ISSUE THREAD

**Issue by coolonce** [efureev/laravel-trees#24]
https://github.com/efureev/laravel-trees/blob/3ff63f9c42a40d46bd60c4ef439399fe02e0831b/src/NestedSetTrait.php#L284

![image](https://user-images.githubusercontent.com/5632461/220584964-e26d37bc-fcb9-4752-b2bb-5ee0c3a79c28.png)

And if change Expression  on this   `$attribute => new Expression($attribute . '+ ' . $delta)`  then it will be all right

**Comment by efureev** [comment]
Could you create a test case with MR?
What's your DB?

because sql works well:
```sql
with exp as (select 10 as attr)

select "attr" + 1
from exp;
```
