### ISSUE TITLE
cannot set column as string

### ISSUE THREAD

**Issue by AjwadA** [efureev/laravel-trees#31]
i tried to set the parent as a string but it keep giving me a uuid.
what i did was:

```
$config = new Base(true);
$config->setAttribute('parent', ParentAttribute::make()->setType('string'));
```

I did looked into the setType function's code and i think its because of the getCastForCustomAttribute function. It has an optional, defaulted false value for the boolean forModel, making always uuid. 

```
$typeOpt = Base::getCastForCustomAttribute($type);

public static function getCastForCustomAttribute(string $attributeType, bool $forModel = false): ?string
    {
        switch ($attributeType) {
            case 'int':
            case 'integer':
            case 'unsignedInteger':
                return 'integer';
            case 'string':
            case 'uuid':
                return $forModel ? 'string' : 'uuid';
        }

        return null;
    }
```

Is there another way to use string instead of uuid?

**Comment by efureev** [comment]
@AjwadA Ulid ? or what type?

**Comment by efureev** [comment]
the default values have been removed specifically to make a closed list of types
