### ISSUE TITLE
Method "App\Models\User::insert" is not supported for inserting new nodes.

### ISSUE THREAD

**Issue by safarovitch** [efureev/laravel-trees#6]
Hi,
I am trying to implement multi tree application for a social media platfom where 
1. every user has multi-endless child user
2. not every user has parent ( multi root)

This pckage seems to be the best I found for laravel 8. 
Unfortunately I am runing into several problem such as.

**1 - When trying to use mutli tree with custom tree configuration as in documentation**
`protected static function buildTreeConfig(): Base`
`    {`
`       return Base::make()`
`            ->setAttributeTree(TreeAttribute::make()->setName('big_tree_id'))`
`            ->setAttribute('parent', ParentAttribute::make()->setName('pid'))`
`            ->setAttribute('left', LeftAttribute::make()->setName('left_offset'))`
`            ->setAttribute('right', RightAttribute::make()->setName('right_offset'))`
`            ->setAttribute('level', LevelAttribute::make()->setName('deeeeep'));`
`    }`

**Simply throws `Call to undefined method Fureev\Trees\Config\Base::make()` Right after php artisan:migrate**

**2 - When registering new user using User::create($attributes)->save()**
Throws `Method "App\Models\User::insert" is not supported for inserting new nodes.`.

**Extra Comment**
I don't know if I am doing anything wrong, must addmit I am new to laravel BUT I am doing everything according to documentation.

**Conclusion**
The documentation may be a little more specific. I am still confused about how to configure mutli root for this package.

Thanks

**Comment by ades4827** [comment]
Same problem, any news?

**Comment by efureev** [comment]
> Hi, I am trying to implement multi tree application for a social media platfom where
> 
> 1. every user has multi-endless child user
> 2. not every user has parent ( multi root)
> 
> This pckage seems to be the best I found for laravel 8. Unfortunately I am runing into several problem such as.
> 
> **1 - When trying to use mutli tree with custom tree configuration as in documentation** `protected static function buildTreeConfig(): Base` ` {` ` return Base::make()` ` ->setAttributeTree(TreeAttribute::make()->setName('big_tree_id'))` ` ->setAttribute('parent', ParentAttribute::make()->setName('pid'))` ` ->setAttribute('left', LeftAttribute::make()->setName('left_offset'))` ` ->setAttribute('right', RightAttribute::make()->setName('right_offset'))` ` ->setAttribute('level', LevelAttribute::make()->setName('deeeeep'));` ` }`
> 
> **Simply throws `Call to undefined method Fureev\Trees\Config\Base::make()` Right after php artisan:migrate**
> 
> **2 - When registering new user using User::create($attributes)->save()** Throws `Method "App\Models\User::insert" is not supported for inserting new nodes.`.
> 
> **Extra Comment** I don't know if I am doing anything wrong, must addmit I am new to laravel BUT I am doing everything according to documentation.
> 
> **Conclusion** The documentation may be a little more specific. I am still confused about how to configure mutli root for this package.
> 
> Thanks

Sorry for the long wait!

If there is no information in the docks , you can look into the tests =)

Answers on you Qs:
1. Call to undefined method Fureev\Trees\Config\Base::make()

It's very strange. Because all tests with this code block - ok.  
for example: `\Fureev\Trees\Tests\Unit\CollectionCustomModelTest::testLinkNodes()`. 

2. You should create a new model as-in-docs: `Page::make($attributes)->save();`
see more: https://github.com/efureev/laravel-trees#creating-nodes

3.  I am still confused about how to configure mutli root for this package.
There are many tests with examples.
Following models use multi-tree: \Fureev\Trees\Tests\models\{Structure, SoftDeleteStructure, Page}

**Comment by efureev** [comment]
I need to be more detailed
