### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ancestor_of' in 'where clause' 

### ISSUE THREAD

**Issue by safarovitch** [efureev/laravel-trees#7]
**Accessing ancestors via**
`$node->ancestors;`
**is throwing following error**

**`Illuminate\Database\QueryException`**
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ancestor_of' in 'where clause' (SQL: select count(*) as aggregate from `users` where `ancestor_of` = {"id":7,"name":"Malcolm Montgomery","username":"6db3f980-b3b4-47ca-ad05-a37cdca8c7ab","email":"wajuca@mailinator.com","email_verified_at":null,"profile_photo_path":null,"lft":3,"rgt":4,"lvl":2,"parent_id":3,"tree_id":2,"created_at":"2021-05-29T14:36:57.000000Z","updated_at":"2021-05-29T14:36:57.000000Z","deleted_at":null,"profile_photo_url":"https:\/\/ui-avatars.com\/api\/?name=Malcolm+Montgomery&color=7F9CF5&background=EBF4FF"}) (View: \resources\views\timeline.blade.php)`

**Comment by david00910** [comment]
Why is this issue closed? Ancestors is still throwing the same error when I try to call the ancestors for a given node. When I use it in a collection resource, it gives me the descendants, not the ancestors of a node..
